platzigram/urls.py
#Django
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static 

from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('posts.urls', 'posts'), namespace='posts')),

    path('users/', include(('users.urls', 'users'),namespace="users")),
        

    


] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

posts/urls.py
"""Post URlS"""
from django.urls import path

#views 
from posts import views

urlpatterns = [
  # Posts
  path( route='', 
        view=views.PostsListView.as_view(),
        name='feed'
  ),  # root
  path( route="posts/new/", 
        view=views.PostCreateView.as_view(), 
        name='create'
  ),
  #Posts
  path(
      route='post/<slug:username>/<int:pk>/',
      view=views.PostDetailView.as_view(),
      name='detail'
  )
]

users/urls.py
"""URL """

# Django
from django.urls import path

# Models
from users import views


urlpatterns = [
  # Users
  path(
    route= 'login/', 
    view = views.LoginView.as_view(), 
    name='login'
  ),

  path(
    route= 'logout/', 
    view = views.LogoutView.as_view(), 
    name='logout'
  ),

  path(
    route= "signup/", 
    view = views.SignupView.as_view(), 
    name="signup"
  ),

  path(
    route= "me/profile/", 
    view=views.ProfileUpdateView.as_view(),
    name="update"
  ),

  #Posts
  path(
    route="user/<str:username>/",
    view=views.UserDetailView.as_view(),
    name="detail"
  ),
]

users/models.py
"""Users model """
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)

  website = models.URLField(max_length=200, blank=True)
  biography = models.TextField(blank=True)
  phone_number = models.CharField(max_length = 20, blank = True)

  picture = models.ImageField(upload_to = 'users/pictures',
                              blank = True, 
                              null=True,
                            )
  created = models.DateTimeField(auto_now_add=True)                        
  modified = models.DateTimeField(auto_now=True)                        

  def __str__(self):
    #Return username    
    return self.user.username

users/forms.py
"""Users forms"""
from django import forms

#Models
from users.models import User
from users.models import Profile


# class ProfileForm(forms.Form):
#   """ Profile Form"""
#   website = forms.URLField(max_length=200, required= True)
#   biography = forms.CharField(max_length=500,required=False)
#   phone_number = forms.CharField(max_length=20,required=False)
#   picture = forms.ImageField()


class SignupForm(forms.Form):
  """ Sign up form"""
  # Por default todos los valores son requeridos 
  username = forms.CharField(min_length=4,max_length=50)
  password = forms.CharField(max_length=70, widget=forms.PasswordInput())
  password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())
  
  first_name = forms.CharField(min_length=2, max_length=50)
  last_name = forms.CharField(min_length=2, max_length=50)
  email = forms.CharField(min_length=6,max_length=70,widget=forms.EmailInput())

  def clean_username(self):
    """Username must be unique"""
    username = self.cleaned_data['username']
    username_taken = User.objects.filter(username=username).exists()
    if username_taken:
      # Django se encarga de capturar este error y elevarlo hasta el html
      raise forms.ValidationError('Username is already in use')

    return username

  def clean(self):
    """Verify password confirmation match  """

    data = super().clean()

    # Debido a que se necesita acceder a dos datos
    password = data['password']
    password_confirmation = data['password_confirmation']

    if password != password_confirmation:
      raise forms.ValidationError('Passwords do not match')

    return data

  def save(self):
    """Create user and profile"""
    data = self.cleaned_data
    data.pop('password_confirmation')

    user = User.objects.create_user(**data)
    user.save()
    profile = Profile(user=user)
    profile.save()

users/views.py
""" User views"""
# to see how to create a custom login https://docs.djangoproject.com/en/2.2/topics/auth/default/#authentication-in-web-requests

#Django
from django.contrib.auth import authenticate, login ,logout
from django.shortcuts import render , redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views


#Views
from django.views.generic.detail import DetailView
from django.views.generic import FormView , UpdateView

#Models
from django.contrib.auth.models import User
from posts.models import Post
from users.models import Profile

#Exceptions
from django.db.utils import IntegrityError

# Forms
from users.forms import SignupForm
# from users.forms import ProfileForm, SignupForm

class LoginView(auth_views.LoginView):
  """Login View"""
  template_name = 'users/login.html'
  redirect_authenticated_user = True


# Create your views here.

# def login_view(request):
#   # Login View
#   if request.method == 'POST':

#     username = request.POST['username']
#     password = request.POST['password']
    
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#       login(request, user)
#       # Redirect to a success page.
#       return redirect('posts:feed')
#     else:
#       # Return an 'invalid login' error message.
#       return render(request, 'users/login.html',{'error':'Invalid username and password'})

#   return render(request,'users/login.html')


# Registrar con clase
class SignupView(FormView):
  """ Users signup view """
  template_name = "users/signup.html"
  form_class = SignupForm
  success_url = reverse_lazy('users:login')
  
  def form_valid(self,form):
    form.save()
    return super().form_valid(form)

# Registrar con metodo
# def signup(request):
#   """Signup View"""

#   # import pdb; pdb.set_trace()
#   if request.method == 'POST':
#     form = SignupForm(request.POST)
#     if form.is_valid():
#       form.save()
#       return redirect('users:login')
#   else:
#     form = SignupForm()

#   return render(
#     request= request, 
#     template_name='users/signup.html',
#     context={
#       'form':form
#     },
#     )


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
  """Log out view"""
  template_name = "users/loggout.html"

@login_required
def logout_view(request):
  """Logout de un user"""
  logout(request)
  return redirect('users:login')


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
  """Update profile view"""
  model = Profile
  template_name = "users/update_profile.html"
  fields = ['website', 'biography', 'phone_number', 'picture']

  def get_object(self):
    """Return user's profile """
    return self.request.user.profile

  def get_success_url(self):
    """Return to user's profile"""
    username = self.object.user.username
    return reverse('users:detail', kwargs={'username': username})



# @login_required
# def update_profile(request):
#   """Update a user's profile view."""
#   profile = request.user.profile
  
#   if request.method == 'POST':
#     form = ProfileForm(request.POST,request.FILES)
#     if form.is_valid():
#       data = form.cleaned_data

#       profile.website = data['website']
#       profile.phone_number = data['phone_number']
#       profile.biography = data['biography']
#       profile.picture = data['picture']
#       profile.save()
    
#       url = reverse('users:detail', kwargs={'username': request.user.username})
#       return redirect(url)
#   else:
#     form = ProfileForm()
  
#   return render(
#     request = request,
#     template_name = 'users/update_profile.html',
#     context = {
#       'profile': profile,
#       'user': request.user,
#       'form': form,
#     }
#   )



# Class views
class UserDetailView(LoginRequiredMixin, DetailView):
  """USer detail view"""
  template_name = 'users/detail.html'
  slug_field = 'username'
  slug_url_kwarg = 'username' #mismo nombre que en el url
  queryset = User.objects.all()

  context_object_name = 'user'

  def get_context_data(self, **kwargs):
    """Add users posts to context"""
    context = super().get_context_data(**kwargs)
    user = self.get_object()
    context["posts"] = Post.objects.filter(user=user).order_by('-created')
    return context
  

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include "layouts/meta/head.html" %}
    {% block head_content %}
    
    
    {% endblock %}

    {% include "layouts/meta/styles.html" %}

</head>
{% load static %} 

<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}
                
                {% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "layouts/base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img 
                    src="{{ user.profile.picture.url }}"  
                    alt="@{{ user.username}}" 
                    class="rounded-circle" 
                    width="150px" 
                    height="150px"
                />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if request.user == user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>
    <div class="container" id="user-posts">
        <div class="row mt-3">  
            {% for post in posts %}
                <div class="col-sm-4 p-5 d-flex justify-content-center align-items-center">
                    <a href="{% url "posts:detail" pk=post.pk username=post.user.username %}" class="border">
                        <img src="{{post.photo.url}}" alt="{{post.title}}" class="img-fluid">
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends 'users/base.html' %}

{% block head_content %}
<title>Platzigram sign in</title>
{% endblock head_content %}

{% block container %}

  {% if form.errors %}
    <p class="alert alert-danger"> 
      User and Password didn't match. Please try again    
    </p>
  {% endif %}

  {% comment %} 
  url Busca la url que tenga ese nombre
  para transformarlo en una url normal

  {% endcomment %}
  <form method="POST" action="{% url "users:login" %}">
    {% comment %} {% csrf_token %} hace un get por un token de autenticacion de url para evitar que se hagan submit de formularios de forma externa ,previniendo así ataques al servidor {% endcomment %}
    {% csrf_token %}
    <div class="form-group">
      <input type="text" class="form-control"  placeholder="Username" name="username">

    </div>
    <div class="form-group">
      <input type="password" class="form-control"  placeholder="Password" name="password">  

    </div>
    <button class="btn btn-primary btn-block mt-5" type="submit">
      Sign in!
    
    </button>    
    <p class="mt-4">
      Dont Have an account yet? 
      <a href="{% url 'users:signup' %}">
        Sign up here.
      </a>
    </p>

  </form>

{% endblock%}

templates/users/signup.html
{% extends 'users/base.html' %}

{% load widget_tweaks %}

{% block head_content %}
    <title>
      Platzigram Signup
    </title>    
{% endblock head_content %}


{% block container %}

  {% if errors %}
    <p class="alert alert-danger">{{errors}}</p>
  {% endif %}
  <h1 class="text-center">
    Sign up!
  </h1>
  <form action="{% url 'users:signup' %}" method="POST" >
    {% csrf_token %}

    {% for field in form  %}
      <div class="form-group">
        {% render_field field|add_error_class:"is-invalid" placeholder=field.label class+="form-control" %}
        {% if field.errors %}
          <div class="invalid-feedback">
            {% for error in field.errors %}{{ error }}{% endfor %}
          </div>
        
        {% endif %}
      
      </div>
    {% endfor %}

    
    <button class="btn btn-primary btn-block mt-5" type="submit">
      Register
    </button>


  </form>
{% endblock container%}

templates/users/update_profile.html
{% extends 'layouts/base.html' %}
{% load static %} 

{% block head_content %}

<title>@{{ request.user.username }} | Update profile</title>
{% endblock head_content %}

{% block container %}


  <div class="container">

    <div class="row justify-content-md-center">
      <div class="col-6 p-4" id="profile-box">

        <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          {% comment %}  {% if form.errors %}
            <p class="alert alert-danger">
              {{form.errors}}
            </p>
          {% endif %}  {% endcomment %}

          <div class="media">
            
            {% if profile.picture %}
              <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />

            {% else %}

              <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />

            {% endif %}

            <div class="media-body">
              <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
              <p class="ml-4"><input type="file" name="picture" {% if not profile.picture %}required="true"{% endif %} ></p>
            </div>
          </div>
          {% for error in form.picture.errors %}
            <div class="alert alert-danger">
              <b>Picture: </b> {{error}}
            </div>
          {% endfor %}

          <hr><br>
          {# Website Field  #}
          <div class="form-group">
              <label>Website</label>
              <input
                  class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                  type="text"
                  name="website"
                  placeholder="Website"
                  value="{% if form.errors %}{{form.website.value}}{% else %}{{ profile.website }}{% endif %}"
              />
              <div class="invalid-feedback">
                {% for error in form.website.errors %}
                  {{error}}
                {% endfor %}
              </div>

          </div>
          {# Biography Filed#}

          <div class="form-group">
            <label>Biography</label>
            <textarea 
              class="form-control {% if form.biography.errors %}is-invalid{% endif %}" 
              name="biography"
            >{% if form.errors %}{{form.biography.value}}{% else %}{{ profile.biography }}{% endif %}</textarea>
            <div class="invalid-feedback">
              {% for error in form.biography.errors %}
                {{error}}
              {% endfor %}
            </div>
          </div>

          {# Phone Number Field#}
          <div class="form-group">
              <label>Phone number</label>
              <input
                  class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                  type="text"
                  name="phone_number"
                  placeholder="Phone number"
                  value="{% if form.errors %}{{form.phone_number.value}}{% else %}{{ profile.phone_number }}{% endif %}"
              />
              <div class="invalid-feedback">
              {% for error in form.phone_number.errors %}
                {{error}}
              {% endfor %}
            </div>
          </div>


                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
  </div>

{% endblock container %}